### PR TITLE
Producer.send message input type added

### PR DESCRIPTION
**Pull request by qvantor**
## Description
Added `message` type support in `.send` method
## Motivation and Context
https://github.com/bbc/sqs-producer/issues/51
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
## Checklist:
- [x] My code follows the code style of this project.
- [x] My change DONT requires a change to the documentation.
- [x] I have read the **CONTRIBUTING** document.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by qvantor** [comment]
@jeanrauwers @nspragg @koresar Could you review changes, please?

**Comment by koresar** [comment]
Looks perfect to me. But I'm not a maintainer mate. I'm like you - an inpatient contributor. 😀

**Comment by jeanrauwers** [comment]
Sorry guys we are having to do lots into our inner source as well! 
but thanks for your PR it looks fine to me! 👍

**Comment by vorticalbox** [comment]
when will this be released to npm?

**Pull request merged**
