### PR TITLE
Add support for DelaySeconds and MessageAttributes props

### PR DESCRIPTION
**Pull request by dieppe**
Hi!

Based on the work of @athibaud, I added the support for DelaySeconds and MessageAttributes.

I did not have time to add any test, but I wanted to know first if this was of any interest for you, and if you'd like to merge the pull request once I provide some tests.

Have a nice one,

Clément

### CODE REVIEW

**Comment by dieppe** [comment]
Any thoughts?

**Comment by robinjmurphy** [comment]
Hi @dieppe. I don't see any reason for not adding this. Would you be able to add a couple of tests to check that the parameters are passed through to the SQS call (example here https://github.com/BBC/sqs-producer/blob/master/test/producer.js#L77) and one for when an invalid parameter is provided?

**Comment by athibaud** [comment]
tests were well needed ;)

**Comment by robinjmurphy** [comment]
Thanks @dieppe and @athibaud. I'll merge and create a new release.

**Comment by robinjmurphy** [comment]
This has now been released to npm as version 1.3.0.

**Comment by athibaud** [comment]
thanks! :beers:

**Pull request merged**
