### PR TITLE
Import only the sqs client from the aws-sdk

### PR DESCRIPTION
**Pull request by gregory**
This will reduce bundle sizes by only importing what's needed from the sdk.

### CODE REVIEW

**Comment by gregory** [comment]
hey @DiegoRBaquero - thanks for taking the time to look into this. 
We are using webpack and are in the process of slimming down our server side bundle. 
Let me know if i can help with anything.
Cheers.

**Comment by gregory** [comment]
By the way @DiegoRBaquero , the package-lock.json wasn't committed - should i add that in a .gitignore or remove it from this PR?

**Comment by DiegoRBaquero** [comment]
Ah ok, cool. It should be removed, as this it is useless in modules. Maybe also add it in .gitignore.

Keep in my I'm not a member of this module, I just have contributed to it :)

**Comment by gregory** [comment]
got it - thanks!

**Comment by nspragg** [comment]
@gregory - cheers

**Pull request merged**
