### PR TITLE
Attach failed message ids to error object

### PR DESCRIPTION
**Pull request by knicola**
**Description:**
Throw a custom error, when messages fail to send, with an additional property to expose the failed message ids for programmatic access.

**Type of change:**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

**Why is this change required?:**
In cases where we have to take additional steps for the failed messages, we have to parse the error message in order to get their IDs.

**Code changes:**

- Add a custom `FailedMessagesError` error class, with a `failedMessages` property of type `string[]` to hold the IDs of the messages that failed to send.

---

**Checklist:**

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by nicholasgriffintn** [comment]
Hey, sorry, super busy this week, I'm gonna slot some time to look into this on Friday hopefully, if not before.

**Comment by knicola** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by knicola** [comment]
¯\_(ツ)_/¯

**Comment by vizeke** [comment]
I suggest saving the entire `BatchResultErrorEntry` from the sqs.send response in the FailedMessagesError. This way will be easier to track what's going wrong.

**Review by nicholasgriffintn — APPROVED** [review]
Sorry I just realised that I am super late here, sorry, holiday and crazy work period.

This looks fine to me, although I do need to investigate if this is potentially breaking, probably not.

**Comment by nicholasgriffintn** [comment]
Merging the live, will mark this as a major change just to be safe.

**Pull request merged**
